/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	"github.com/pkg/errors"

	"github.com/upbound/upjet/pkg/resource"
	"github.com/upbound/upjet/pkg/resource/json"
)

// GetTerraformResourceType returns Terraform resource type for this Pg
func (mg *Pg) GetTerraformResourceType() string {
	return "aiven_pg"
}

// GetConnectionDetailsMapping for this Pg
func (tr *Pg) GetConnectionDetailsMapping() map[string]string {
	return map[string]string{"pg[*].password": "status.atProvider.pg[*].password", "pg[*].replica_uri": "status.atProvider.pg[*].replicaUri", "pg[*].uri": "spec.forProvider.pg[*].uriSecretRef", "pg_user_config[*].admin_password": "spec.forProvider.pgUserConfig[*].adminPasswordSecretRef", "pg_user_config[*].migration[*].password": "spec.forProvider.pgUserConfig[*].migration[*].passwordSecretRef", "service_password": "status.atProvider.servicePassword", "service_uri": "status.atProvider.serviceUri"}
}

// GetObservation of this Pg
func (tr *Pg) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this Pg
func (tr *Pg) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this Pg
func (tr *Pg) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this Pg
func (tr *Pg) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this Pg
func (tr *Pg) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this Pg using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *Pg) LateInitialize(attrs []byte) (bool, error) {
	params := &PgParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *Pg) GetTerraformSchemaVersion() int {
	return 0
}
